# 检测平台
if(CMAKE_SYSTEM_NAME STREQUAL "Android")
    set(PLATFORM_ANDROID ON)
elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS" OR CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND IOS)
    set(PLATFORM_IOS ON)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(PLATFORM_WINDOWS ON)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(PLATFORM_LINUX ON)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(PLATFORM_MACOS ON)
endif()

message(STATUS "Building for platform: ${CMAKE_SYSTEM_NAME}")