name: Main

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04

    # 需要设置写权限才能自动发布
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 上传附件
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

      # 发布release版本
      - name: Release version
        uses: ncipollo/release-action@v1
        if: github.event_name == 'release'
        with:
          allowUpdates: true
          artifacts: path/to/artifact/world.txt
          token: ${{ secrets.GITHUB_TOKEN }}